{% set name = "gobject-introspection" %}
{% set version = "1.64.1" %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://download.gnome.org/sources/{{ name }}/{{ '.'.join(version.split('.')[:2]) }}/{{ name }}-{{ version }}.tar.xz
  sha256: 80beae6728c134521926affff9b2e97125749b38d38744dc901f4010ee3e7fa7
  patches:
    - meson-rpaths.patch  # [linux]
    - gcc7-rpath-link.patch  # [linux]
    - test-fix.patch  # [linux]

build:
  number: 2
  skip: true  # [py<35]

requirements:
  build:
    - {{ posix }}bison
    - {{ posix }}flex
    - ninja
    - {{ posix }}patch
    - {{ native }}pkg-config
    - {{ compiler('c') }}
  host:
    - meson
    - cairo
    - gettext  # [osx]
    - glib
    - libffi
    - python
  run:
    - glib
    - libffi
    - python

test:
  requires:
    - pkg-config
  commands:
    - conda inspect linkages -p $PREFIX $PKG_NAME  # [not win]
    - conda inspect objects -p $PREFIX $PKG_NAME  # [osx]
    - g-ir-scanner --help  # [not win]
    - python "%PREFIX%\\Library\\bin\\g-ir-scanner" --help  # [win]
    - g-ir-compiler --help

    # check that g-ir-scanner can be found through pkg-config (used by downstream builds)
    - test -f `pkg-config --variable=g_ir_scanner --dont-define-prefix gobject-introspection-1.0`  # [unix]
    - for /f "usebackq tokens=*" %%a in (`pkg-config --variable=g_ir_scanner --dont-define-prefix gobject-introspection-1.0`) do if not exist "%%a" exit 1  # [win]

about:
  home: https://wiki.gnome.org/action/show/Projects/GObjectIntrospection
  license: LGPL-2.0-or-later
  license_family: LGPL
  license_file: COPYING
  summary: 'Middleware for binding GObject-based code to other languages.'

extra:
  recipe-maintainers:
    - pkgw
    - ocefpaf
    - scopatz
    - tschoonj
